// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXgBHfEF8rtgJFpeuqr0hPzJNV4WMcCi8',
    appId: '1:896020039801:web:86f25970604f327d376ca8',
    messagingSenderId: '896020039801',
    projectId: 'chat-app-c79ec',
    authDomain: 'chat-app-c79ec.firebaseapp.com',
    storageBucket: 'chat-app-c79ec.firebasestorage.app',
    measurementId: 'G-MX5E6LDEXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2hzCzCt_1RXux5eUu0bqUhSylWKRK2dE',
    appId: '1:896020039801:android:ef02ba057c764ad2376ca8',
    messagingSenderId: '896020039801',
    projectId: 'chat-app-c79ec',
    storageBucket: 'chat-app-c79ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfXBZNJqS__jN1JOUEch3dHBnv7xgFxYs',
    appId: '1:896020039801:ios:f1817b44cca1efd3376ca8',
    messagingSenderId: '896020039801',
    projectId: 'chat-app-c79ec',
    storageBucket: 'chat-app-c79ec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfXBZNJqS__jN1JOUEch3dHBnv7xgFxYs',
    appId: '1:896020039801:ios:f1817b44cca1efd3376ca8',
    messagingSenderId: '896020039801',
    projectId: 'chat-app-c79ec',
    storageBucket: 'chat-app-c79ec.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXgBHfEF8rtgJFpeuqr0hPzJNV4WMcCi8',
    appId: '1:896020039801:web:e8b47fde96625c13376ca8',
    messagingSenderId: '896020039801',
    projectId: 'chat-app-c79ec',
    authDomain: 'chat-app-c79ec.firebaseapp.com',
    storageBucket: 'chat-app-c79ec.firebasestorage.app',
    measurementId: 'G-QXFYVJF8G6',
  );
}
